# Site settings
title: Arjen.me
email: mail@arjen.me
description: Arjen Oosterkamp - Full stack web developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arjen.me" # the base hostname & protocol for your site
paginate: 10
paginate_path: "/blog/page/:num"
permalink: /blog/:title

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'spec']

assets:
  baseurl: http://arjeno.github.io/arjeno.github.io/assets

  sources:
    - _assets/stylesheets
    - _assets/images
