source 'https://rubygems.org'
ruby '2.2.0'
gem 'bundler'
# gem 'jekyll'
# gem 'rack-jekyll'
# gem 'kramdown'
gem 'github-pages'
gem 'puma'
gem 'rake'
gem 'rack-contrib'
gem 'rack-cors'
gem 'rack-rewrite'
gem 'jekyll-assets'
gem 'jekyll-sitemap'
